update_rate: 1

## Multipliers for Delta tiers
## increases a measurements threshold to be added to the buffer by the given amount
delta_tiers: [1,2,3,4,5,6,7,8,9,10]

## Measurement topics
measurement_topics:
  sonar: sonar_processing/target_list/associated

strapdown_topic: odometry/filtered/odom # To disable, set to None

### Buffer space configurations ###
buffer_space:
  capacity: 29 # Total capacity
  burst: 3

use_control_input: False

### Initial Mean Estimate Configurations ###
default_starting_position:
  x: 0.0
  y: 0.0
  z: -1.0
  x_vel: 0.0
  y_vel: 0.0
  z_vel: 0.0

### Process Noise Configurations ###
process_noise:
  ownship:
    x: 0.3
    y: 0.3
    z: 0
    x_vel: 0.1
    y_vel: 0.1
    z_vel: 0.1
  blueteam:
    x: 0.5
    y: 0.5
    z: 0
    x_vel: 0.1
    y_vel: 0.1
    z_vel: 0.1
  redteam:
    x: 0.1
    y: 0.1
    z: 0
    x_vel: 0.01
    y_vel: 0.01
    z_vel: 0.01

### Initial Uncertainty Configurations ###
initial_uncertainty:
  ownship:
    x: 2.0
    y: 2.0
    z: 0.1
    x_vel: 0.1
    y_vel: 0.1
    z_vel: 0.1
  # for asset positions provided to us through roslaunch params
  known_starting_position: 
    x: 2.0
    y: 2.0
    z: 0.1
    x_vel: 0.1
    y_vel: 0.1
    z_vel: 0.1
  # asset positions not provided in roslaunch, including redteam
  unknown_starting_position: 
    x: 1000
    y: 1000
    z: 0.00001
    x_vel: 0.2
    y_vel: 0.2
    z_vel: 0.00001
